### PR TITLE
Restored FOP auto discovery service files added configuration method to accept foUserAgent

### PR DESCRIPTION
**Pull request by rack197**

### CODE REVIEW

**Comment by rototor** [comment]
As I don't use FOP at all, and also no longer this project, I have no idea if the changes really work.

But I'll merge it anyway. Should not hurt.

**Comment by rack197** [comment]
Many thanks for your fast response and also thank you for your work. 
Would you think it is possible for you to publish 3.1.5 to mvn central ?

**Comment by rototor** [comment]
Well, I tried to push out a release. But I had test failures. So I have to investigate whats going there... 

Hopefully I find some time on Sunday, but I can not guarantee that. Sorry.

**Comment by rack197** [comment]
No worries thank you !

**Pull request merged**
